export { default as footer } from './footer';
export { default as landing } from './landing';
export { default as error } from './error';
export { default as contacts } from './contacts';
export { default as about } from './about';
export { default as stages } from './stages';
export { default as portfolio } from './portfolio';
export { default as preloader } from './preloader';
export { default as mood } from './mood';
